apiVersion: v1
kind: Service
metadata:
  name: opentabletop-server
  labels:
    app: opentabletop
    component: server
spec:
  type: ClusterIP
  selector:
    app: opentabletop
    component: server
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
